# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: icanhazip

builds:
- id: icanhazip
  main: .
  binary: golang-icahazip
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -extldflags "-static" -X "main.version={{.Version}}"
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - "386"
    - arm64
    - arm
  ignore:
    - goos: darwin
      goarch: "386"
    - goos: windows
      goarch: arm
  
nfpms:
- id: packages
  ids:
    - icanhazip
  package_name: icanhazip
  file_name_template: "icanhazip-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
  vendor: charliemaiors
  homepage: https://github.com/charliemaiors/icanhazip
  maintainer: charliemaiors
  bindir: /usr/local/bin
  description: |-
    Icahanzip implementation in Golang
  license: Apache 2.0
  formats:
    - deb
    - rpm
    - archlinux
    - apk
  contents:
    - src: packaging/systemd/icahazip.service
      dst: /usr/lib/systemd/system/icahazip.service
    - src: packaging/config/config.yaml
      dst: /etc/icanhazip/config.yaml
      type: config|noreplace
  scripts:
    preinstall: packaging/scripts/preinstall.sh
    preremove: packaging/scripts/preremove.sh
release:
  mode: keep-existing
  footer: "Released with passion and GoReleaser"

kos:
  - id: docker
    build: icanhazip
    repositories: 
    - ghcr.io/charliemaiors/icanhazip
    local_domain: ghcr.io
    disable: "{{ .IsSnapshot }}"
    main: .
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64