server:
  port: 8091
  host: 0.0.0.0
  tls:
    cert_file: /etc/icanhazip/cert.pem
    key_file: /etc/icanhazip/key.pem
results:
  include_private: true
  http_headers:
    - "X-Forwarded-For"
    - "X-Real-IP"
  